name: PlayerIPWhitelist
version: '${project.version}'
description: A 2nd security method for DogGate SMP by hungaz lul.
author: hungnguyennaz
main: me.hungaz.PlayerIPWhitelist
api-version: 1.13
folia-supported: true
